apiVersion: v1
kind: ConfigMap
metadata:
  name: laibin-screen-config
  namespace: default
data:
  default.conf: |
    server {
      listen       80 default_server;
      listen  [::]:80 default_server;
      root /usr/share/nginx/html;
      index index.html index.htm;

      location /api/ {
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
        add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';

        if ($request_method = 'OPTIONS') {
          return 204;
        }

        proxy_pass http://172.25.148.179:9510/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Ng:inX-Proxy true;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_redirect off;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }

    }

