apiVersion: v1
kind: Service
metadata:
  name: laibin-screen
spec:
  selector:
    app: laibin-screen
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32000
  type: NodePort

